### ISSUE TITLE
Sites keep loading

### ISSUE THREAD

**Issue by Obamagrilledcheese** [killsecurly/ONC#2]
Everything works until I try to go to any website. (Google classroom, coolmathgames, anything else). It just starts loading forever.

**Comment by killsecurly** [comment]
Use a DNS server, in Advanced. Put in `8.8.8.8` and `8.8.4.4` for Google's public DNS servers. It seems like you are trying to use a DNS server that is currently down or sometimes working, as spotted by my testing team. I put those two IPs and it works fine right now.

How To:
Follow the same steps in the README, then in the website, click `Advanced +`. If you click on it, an options panel will slide up. There will be an IP address there. Delete it and replace it with `8.8.8.8`. Go to the next line, and put in `8.8.4.4`.

**Comment by Obamagrilledcheese** [comment]
After doing that, google search works but websites still load forever.

**Comment by killsecurly** [comment]
> After doing that, google search works but websites still load forever. Maybe it doesn't work for certain schools?

Try putting your school's DNS IP address to the list. That might resolve the other websites. Or, you can try Cloudflare's public DNS, `1.1.1.1`.

**Comment by killsecurly** [comment]
@Obamagrilledcheese
The error is now fixed. I changed the DNS servers to nginx DNS servers to be more stable.
