### ISSUE TITLE
Password?????

### ISSUE THREAD

**Issue by SquaredNES** [killsecurly/ONC#22]
what does it mean by password? what is the password? please help

**Comment by SquaredNES** [comment]
wait nvm i can just go to protected.html and it works

**Comment by somethingbutnot** [comment]
killsecurlyfoundation is the password btw

**Comment by killsecurly** [comment]
> wait nvm i can just go to protected.html and it works

Yeah. It's just a way to deter off people that won't actually try to use ONC properly.
